### PR TITLE
Multi instances improvement and Traefik ready

### PR DESCRIPTION
**Pull request by mmallejac**
Hi Tim,

As discussed, here a a set of modifications to allow multiple instances to run ok and also a docker-compose ready to be used with [Traefik](https://containo.us/traefik/).

To better accommodate different use cases, I've provided 3 version of the compose file, see the README.md file.

The `setup` container has disappeared, in favor of an improved `docker-entrypoint.sh`.

I have two Foswiki + Solr instances running on my docker server, behind Traefik. 
For these, the setup is not 100% byte-per-byte the same as the one proposed here, because I had to make my setup work before I could work on this PR. So this setup may have a small glitch or two. 
If you like this PR, I'll make sure that it is fully operational.

Hope you like it !

Michel :-)

### CODE REVIEW

**Comment by timlegge** [comment]
Initial view looks fine.  I have been busy with some other items and will be for another week but I will try to do some additional review and testing.

I don't see any reason not to merge though at first look

**Comment by mmallejac** [comment]
Hi Tim,

Thanks for the feedback.
Sounds good to me, take your time. My two instances are running great.

Take care,
Michel

Le mar. 10 mars 2020 à 12:41, Timothy Legge <notifications@github.com> a
écrit :

**Comment by mmallejac** [comment]
Hello Tim,

How are you doing during these strange times ?? Here in Switzerland we've
all at home, all is ok for me and family (including the ones in Montréal).
Did you get any chance to review my PR ?

Cheers,
Michel

Le mar. 10 mars 2020 à 13:29, Michel Mallejac <Michel.Mallejac@gmail.com> a
écrit :

**Comment by timlegge** [comment]
Glad to hear things are fine in Switzerland it is indeed strange times.  I have only been out of the house once since Sunday.   

I will look now and like commit it.  I have created a irc channel on freenode #timlegge-docker-foswiki that I monitor (only me there as I had not gotten around to telling anyone it was there).  A little more real time when the timezones line up.  I am using quassel so I see any messages sent while I am not on line

I also added you as a collaborator on this project.  Kind of make sense sine you know more than I do about docker compose

**Comment by mmallejac** [comment]
Hi Tim,

Thanks a lot for all of this, really appreciated.
Any idea for further improvements ? The repo has got a little bit of
popularity, that's neat !

Le ven. 27 mars 2020 à 23:37, Timothy Legge <notifications@github.com> a
écrit :

**Comment by timlegge** [comment]
Hi

I have not given it a lot of thought recently as it works for me :-) but I
focused on getting all the perl modules required into Alpine Linux so
thats done.  I had considered looking at apache as opposed to nginx but I
can't think of a good reason to do so.   I do need to upgrade the SOLR
items, I sent Michael Daum the necessary config change and I might look at
adding something to the docker compose to allow you to choose the solr
version

Tim

**Comment by mmallejac** [comment]
Sounds good ! I am also very interested in a deeper understanding of Solr,
since I need it for our main professional project : we plan to index files
content as well as our ERP mariadb database. Which version will you target ?

I know quite well Apache, but not at all Nginx. From what I've read, Nginx
is considered better for serving static files whereas Apache would be
better for more complex stuff.
Does Foswiki recommend Apache over Nginx ? I know this topic -
https://foswiki.org/Support.ApacheConfigGenerator - and it does not seem to
have the Nginx counterpart.
Not sure about the real benefit of switching from one to another.

I could also add another third party container into our mix :
https://github.com/fradelg/docker-mysql-cron-backup
I am currently integrating it into our Nextcloud setup. I like the fact
that it is able to keep the n last backups and has a restore option
included as well.

Are you aware of Michael Daum progress on his Natskin new release ? I love
it a lot and can't wait to see the new version... :-)

Michel

Le mar. 31 mars 2020 à 19:34, Timothy Legge <notifications@github.com> a
écrit :

**Pull request merged**
