### PR TITLE
simple docker-compose for https support

### PR DESCRIPTION
**Pull request by timlegge**
Hi

Can you take a look at this?  I often need a quick and dirty way to test SAML support and it required SSL.  

You will need a hosts file entry to point docker-foswiki.local to your local IP.

https://docler-foswiki.local:8443

Tim

### CODE REVIEW

**Comment by mmallejac** [comment]
Hi Tim,

Looks good to me ! Works great.
A few suggestions : 

- new docker-compose file extension `.yml` instead of `.yaml`
- have the 4 docker-compose files numbered 1 2 3 4 (the new would be the # 2)
- explain this addition in the doc, including : 
  - some words about SAML
  - the command you have generated the self-signed certificate with

**Comment by timlegge** [comment]
Thanks a lot.  I will add the updates later today

**Comment by timlegge** [comment]
> You didn't mention SAML here, maybe it would have been a good thing ?

SAML is just really the reason that I needed https.  I did realize that I do need to do some better documentation on the Foswiki SAML implementation as well and also not enable certaing plugins lie LDAP and SAML by default.

Tim

**Comment by mmallejac** [comment]
One step at a time :-)


Le ven. 10 avr. 2020 à 21:05, Timothy Legge <notifications@github.com> a
écrit :

**Pull request merged**
