### PR TITLE
Add nat skin solr8

### PR DESCRIPTION
**Pull request by mmallejac**
Testing PR with a few modifications in the README file : docker-compose, removed some `sudo`, a few things

### CODE REVIEW

**Comment by mmallejac** [comment]
Not sure what's that ! hope that I have not broken anything ?

**Comment by timlegge** [comment]
Merged.  Thanks

**Comment by timlegge** [comment]
I merger the changes with a couple of typo fixes.  Not sure about the
removal of sudo as I have never fully sorted out my permissions on Ubuntu...

**Comment by timlegge** [comment]
Actually did you make changes for natskin?  It was only the readme in this PR

**Comment by mmallejac** [comment]
Thanks !

Yes, that was just a test for me, first time I do a PR :-)
I will work on NatSkin this afternoon

On my setup, I do not need sudo, except when I wan to access a Docker
volume from the host : /var/lib/docker/volumes/...
My user belongs to the docker group

Le ven. 15 nov. 2019 à 13:04, Timothy Legge <notifications@github.com> a
écrit :

**Pull request merged**
